import Link from 'next/link'
import { ArrowRight, MapPin } from 'lucide-react'
import { AccentHeading, AudioHint, ContentSection, DecorativeRule, HeaderBand, ImageCredit, ImageFrame, ImageMosaic, InfoLine, MapLabel, PageFrame, PagePattern, PrimaryButton, SectionKicker, Stat, TextQuote } from '@/components/site-shell'

export default function HomePage() {
  return <PageFrame>
    <PagePattern><section className="relative overflow-hidden bg-primary text-primary-foreground"><div className="mx-auto grid min-h-[640px] max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-[1.08fr_.92fr] lg:px-8 lg:py-24"><div className="relative z-10"><SectionKicker>Đời sống tinh thần của dân tộc Nùng An</SectionKicker><h1 className="max-w-3xl font-serif text-6xl leading-[.94] tracking-tight md:text-8xl">Từ núi rừng,<br /><span className="text-accent">một sắc chàm</span><br />được dệt nên.</h1><p className="mt-8 max-w-xl text-base leading-8 text-primary-foreground/75">Một hành trình tìm hiểu con người Nùng, cộng đồng của những bản làng miền Đông Bắc, nơi tiếng hát, bếp lửa, nếp áo và niềm tin cùng kể một câu chuyện về cội nguồn.</p><div className="mt-9 flex flex-wrap items-center gap-5"><PrimaryButton href="#tim-hieu">Bắt đầu hành trình</PrimaryButton><AudioHint /></div></div><div className="relative min-h-[420px]"><div className="absolute inset-x-5 bottom-0 top-5 border border-accent/50" /><div className="absolute inset-x-10 bottom-5 top-0 border border-primary-foreground/20" /><div className="relative h-[420px] overflow-hidden border-8 border-primary"><img src="/ruong-bac-thang.jpg" alt="Ruộng bậc thang và tư liệu giới thiệu người Nùng" referrerPolicy="no-referrer" className="size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-primary/80 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6"><p className="font-mono text-[9px] uppercase tracking-[.22em] text-accent">01 / Tìm hiểu chung</p><p className="mt-2 font-serif text-3xl">Một miền xanh trong ký ức.</p></div></div></div></div><div className="mx-auto flex max-w-7xl justify-between border-t border-primary-foreground/20 px-5 py-5 font-mono text-[9px] uppercase tracking-[.2em] text-primary-foreground/50 lg:px-8"><span>Việt Nam · Đông Bắc</span><span>Cuộn để khám phá ↓</span></div></section></PagePattern>

    <ContentSection><div id="tim-hieu" className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><SectionKicker>01 / Cộng đồng và vùng đất</SectionKicker><AccentHeading>Người Nùng<br /><span className="text-accent">là ai?</span></AccentHeading><DecorativeRule /><p className="text-sm leading-8 text-muted-foreground">Nùng là một trong 54 dân tộc Việt Nam, thuộc nhóm ngôn ngữ Tày–Thái. Cộng đồng cư trú tập trung ở Cao Bằng, Lạng Sơn, Bắc Kạn, Thái Nguyên, Tuyên Quang, Hà Giang và một số tỉnh miền núi phía Bắc.</p><div className="mt-7 flex flex-wrap gap-2"><MapLabel><MapPin className="mr-2 size-3" /> Cao Bằng</MapLabel><MapLabel>Lạng Sơn</MapLabel><MapLabel>Bắc Kạn</MapLabel><MapLabel>Thái Nguyên</MapLabel></div></div><div className="grid gap-x-12 gap-y-8 sm:grid-cols-2"><InfoLine label="Ngôn ngữ">Nhiều nhóm địa phương sử dụng các phương ngữ Nùng khác nhau; tiếng nói gần gũi với Tày và các ngôn ngữ Tày–Thái.</InfoLine><InfoLine label="Sinh kế">Canh tác lúa nước ở thung lũng, ruộng bậc thang; trồng ngô, cây màu, chăn nuôi và nghề thủ công.</InfoLine><InfoLine label="Nhà ở và bản làng">Bản thường nằm ven suối hoặc trong thung lũng. Nhà sàn, không gian bếp và sân phơi gắn với đời sống gia đình.</InfoLine><InfoLine label="Cộng đồng">Quan hệ họ hàng, láng giềng và tinh thần tương trợ giúp duy trì nếp sống bản làng qua nhiều thế hệ.</InfoLine></div></div></ContentSection>

    <section className="bg-secondary"><ContentSection><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><SectionKicker>02 / Mảnh ký ức</SectionKicker><AccentHeading>Văn hóa không đứng yên<br /><span className="text-accent">Văn hóa là một dòng chảy liên tục</span></AccentHeading></div><p className="max-w-sm text-sm leading-7 text-muted-foreground">Từ một món ăn trong ngày Tết đến một câu hát giao duyên, bản sắc được nuôi dưỡng bằng những điều gần gũi nhất.</p></div><div className="grid gap-0 border-y border-primary/20 md:grid-cols-4"><article className="border-b border-primary/20 p-6 md:border-b-0 md:border-r"><p className="font-mono text-xs text-accent">01</p><h3 className="mt-8 font-serif text-2xl text-primary">Ẩm thực</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Gạo nếp, thịt hun khói, lạp, xôi màu và các món chế biến từ sản vật miền núi.</p></article><article className="border-b border-primary/20 p-6 md:border-b-0 md:border-r"><p className="font-mono text-xs text-accent">02</p><h3 className="mt-8 font-serif text-2xl text-primary">Tiếng hát</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Sli, lượn, then là những hình thức diễn xướng gắn với giao duyên, lễ hội và nghi lễ.</p></article><article className="border-b border-primary/20 p-6 md:border-b-0 md:border-r"><p className="font-mono text-xs text-accent">03</p><h3 className="mt-8 font-serif text-2xl text-primary">Tín ngưỡng</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Quan niệm về tổ tiên, vía, thần linh và sự cân bằng giữa con người với tự nhiên.</p></article><article className="p-6"><p className="font-mono text-xs text-accent">04</p><h3 className="mt-8 font-serif text-2xl text-primary">Lễ hội</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Lồng tồng, nghi lễ nông nghiệp và các dịp cộng đồng cùng cầu mùa, cầu phúc.</p></article></div></ContentSection></section>

    <section className="bg-primary text-primary-foreground"><ContentSection><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><ImageMosaic large="/am-thuc-nung.jpg" small="/van-nghe-dan-toc-nung-an.jpg" alt="Tư liệu ẩm thực và đời sống tinh thần dân tộc Nùng" /><div><SectionKicker>03 / Đời sống tinh thần</SectionKicker><h2 className="font-serif text-5xl leading-tight md:text-6xl">Khi lời ca<br /><span className="text-accent">gọi mùa về.</span></h2><p className="mt-7 text-sm leading-8 text-primary-foreground/70">Then là một thực hành nghi lễ và nghệ thuật quan trọng của nhiều cộng đồng Tày, Nùng, Thái. Năm 2019, thực hành Then của người Tày, Nùng, Thái ở Việt Nam được UNESCO ghi danh vào Danh sách di sản văn hóa phi vật thể đại diện của nhân loại.</p><div className="mt-9"><Link href="/trang-phuc" className="inline-flex items-center gap-3 border-b border-accent pb-2 font-bold text-accent">Khám phá trang phục <ArrowRight /></Link></div><div className="mt-12 grid grid-cols-2 gap-6 border-t border-primary-foreground/20 pt-6"><Stat number="2019" label="Then được UNESCO ghi danh" /><Stat number="54" label="Dân tộc Việt Nam" /></div></div></div></ContentSection></section>

    <ContentSection><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><SectionKicker>04 / Câu chuyện tiếp nối</SectionKicker><h2 className="font-serif text-5xl leading-tight text-primary">Một bộ áo<br /><span className="text-accent">là một bản đồ.</span></h2><TextQuote>Màu chàm đi cùng đất, nước, bàn tay và thời gian.</TextQuote><p className="mt-7 text-sm leading-8 text-muted-foreground">Trang phục không chỉ là diện mạo. Nó đánh dấu tuổi tác, dịp lễ, vùng cư trú và bàn tay khéo léo của người làm ra nó.</p><Link href="/trang-phuc" className="mt-8 inline-flex items-center gap-2 border-b border-accent pb-2 text-sm font-bold text-primary">Đọc chuyên đề trang phục <ArrowRight /></Link></div><div><ImageFrame src="/khong-gian-nung.jpg" alt="Tư liệu người Nùng và vùng cư trú" className="aspect-[1.25]" /><ImageCredit /></div></div></ContentSection>

    <HeaderBand>Trải nghiệm đang được chuẩn bị</HeaderBand><section className="bg-accent px-5 py-16"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-accent-foreground/70">Tính năng tương tác</p><h2 className="mt-3 font-serif text-4xl text-accent-foreground md:text-5xl">Thử khoác lên mình<br />một sắc chàm dân tộc</h2></div><Link href="/thay-do" className="inline-flex items-center gap-3 self-start border border-accent-foreground/30 bg-accent-foreground px-7 py-4 font-bold text-accent md:self-auto">Mở phòng thay đồ <ArrowRight /></Link></div></section>
  </PageFrame>
}